In [ ]:
'''
'OUTSIDE'- 0
'INSIDE' - 1
'IN_VESTIBULE' - 2
'''

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

from google.colab import drive
drive.mount('/content/drive')

#de = pd.read_csv("drive/My Drive/iBeacon_RSSI_Labeled.csv")
df=pd.read_csv("drive/My Drive/IndoorLocal/out.csv")

Mounted at /content/drive


In [ ]:
df.head()

name locationStatus      timestamp rssiOne rssiTwo
0  FF:FF:C2:1D:9B:54        OUTSIDE  1551367500637     -79     -90
1  FF:FF:C2:1D:9B:54        OUTSIDE  1551367501323     -81     -90
2  FF:FF:C2:1D:9B:54        OUTSIDE  1551367502416     -83     -91
3  FF:FF:C2:1D:9B:54        OUTSIDE  1551367504813     -80     -91
4  FF:FF:C2:1D:9B:54        OUTSIDE  1551367504813     -80     -91

In [ ]:
df.shape

(23570, 5)

In [ ]:
dups = df.duplicated()
df[dups]

name locationStatus      timestamp rssiOne rssiTwo
4      FF:FF:C2:1D:9B:54        OUTSIDE  1551367504813     -80     -91
19     FF:FF:C2:1D:9B:71        OUTSIDE  1551367521690     -82     -89
21     FF:FF:C2:1D:9B:71        OUTSIDE  1551367521690     -82     -89
25     FF:FF:C2:1D:9B:54        OUTSIDE  1551367525583     -80     -90
33     FF:FF:C2:1D:9B:52        OUTSIDE  1551367529538     -84     -90
...                  ...            ...            ...     ...     ...
23447  FF:FF:C2:1D:9B:54        OUTSIDE  1551368664764     -86     -86
23465  FF:FF:C2:1D:9B:52        OUTSIDE  1551368669915     -87     -87
23497  FF:FF:C2:1D:9B:52        OUTSIDE  1551368678049     -84     -84
23501  FF:FF:C2:1D:9B:52        OUTSIDE  1551368678049     -84     -84
23565  FF:FF:C2:1D:9B:52        OUTSIDE  1551368694572     -80     -80

[3717 rows x 5 columns]

In [ ]:
df.drop_duplicates(keep=False, inplace=True)

In [ ]:
df.shape

(17573, 5)

In [ ]:
df.isnull().sum()

name              0
locationStatus    1
timestamp         1
rssiOne           1
rssiTwo           1
dtype: int64

In [ ]:
column_modes = df.mode().iloc[0]

#Replace null values with the corresponding column's mode.
df.fillna(column_modes, inplace=True)

In [ ]:
df.isnull().sum()

name              0
locationStatus    0
timestamp         0
rssiOne           0
rssiTwo           0
dtype: int64

In [ ]:
df.dtypes

name              object
locationStatus    object
timestamp         object
rssiOne           object
rssiTwo           object
dtype: object

In [ ]:
df['rssiOne'] = pd.to_numeric(df['rssiOne'], errors='coerce').astype('Int64')

df['rssiTwo'] = pd.to_numeric(df['rssiTwo'], errors='coerce').astype('Int64')

df['timestamp'] = pd.to_numeric(df['timestamp'], errors='coerce').astype('Int64')

In [ ]:
df.dtypes

name              object
locationStatus    object
timestamp          Int64
rssiOne            Int64
rssiTwo            Int64
dtype: object

In [ ]:
df['locationStatus'].unique()

array(['OUTSIDE', 'IN_VESTIBULE', 'INSIDE', 'locationStatus'],
      dtype=object)

In [ ]:
column_to_check = 'locationStatus'
target_value = 'locationStatus'

count_of_occurrences = df[df[column_to_check] == target_value].shape[0]
print(count_of_occurrences)

1


In [ ]:
column_to_check = 'locationStatus'
target_value = 'locationStatus'

# Delete rows where the value in 'column_name' matches 'target_value'
df = df[df[column_to_check] != target_value]

In [ ]:
df.shape

(17572, 5)

In [ ]:
df['locationStatus'].unique()

array(['OUTSIDE', 'IN_VESTIBULE', 'INSIDE'], dtype=object)

In [ ]:
df['locationStatus'] = df['locationStatus'].replace('OUTSIDE', 0)
df['locationStatus'] = df['locationStatus'].replace('INSIDE', 1)
df['locationStatus'] = df['locationStatus'].replace('IN_VESTIBULE', 2)

In [ ]:
df.dtypes

name              object
locationStatus     int64
timestamp          Int64
rssiOne            Int64
rssiTwo            Int64
dtype: object

In [ ]:
df.head

<bound method NDFrame.head of                     name  locationStatus      timestamp  rssiOne  rssiTwo
0      FF:FF:C2:1D:9B:54               0  1551367500637      -79      -90
1      FF:FF:C2:1D:9B:54               0  1551367501323      -81      -90
2      FF:FF:C2:1D:9B:54               0  1551367502416      -83      -91
5      FF:FF:C2:1D:9B:54               0  1551367506037      -77      -90
6      FF:FF:C2:1D:9B:54               0  1551367508214      -75      -90
...                  ...             ...            ...      ...      ...
23564  FF:FF:C2:1D:9B:71               0  1551368693080      -93      -93
23566  FF:FF:C0:22:3D:C1               0  1551368694032      -89      -89
23567  FF:FF:C2:1D:9B:54               0  1551368694210      -78      -78
23568  FF:FF:C2:1D:9B:71               0  1551368694011      -91      -91
23569                                 0  1551367677184      -86      -86

[17572 rows x 5 columns]>

In [ ]:
df['name'].unique()

array(['FF:FF:C2:1D:9B:54', 'FF:FF:C2:1D:9B:71', 'FF:FF:C2:1D:9B:52',
       'FF:FF:C0:22:3D:C1', 'FF:FF:C0:21:F1:2B', 'FF:FF:C2:1E:05:19',
       'FF:FF:C2:1E:02:D2', 'FF:FF:C0:21:EF:A4', 'FF:FF:C0:21:F1:31',
       'FF:FF:C0:21:EF:1A', 'FF:FF:C0:21:EF:BF', 'FF:FF:C0:21:EF:BA',
       '\x1a'], dtype=object)

In [ ]:
#VISUALIZING
import matplotlib.pyplot as plt
import plotly.express as px

for col in df.columns:
  fig=px.histogram(df,x=col)
  fig.show()

In [ ]:
#Checking outliers
import matplotlib.pyplot as plt
import plotly.express as px

for col in df.columns:
  fig=px.box(df,y=col)
  fig.show()

In [ ]:
import re
df = df.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
df.head()

name  locationStatus      timestamp  rssiOne  rssiTwo
0  FF:FF:C2:1D:9B:54               0  1551367500637      -79      -90
1  FF:FF:C2:1D:9B:54               0  1551367501323      -81      -90
2  FF:FF:C2:1D:9B:54               0  1551367502416      -83      -91
5  FF:FF:C2:1D:9B:54               0  1551367506037      -77      -90
6  FF:FF:C2:1D:9B:54               0  1551367508214      -75      -90

In [ ]:
# get the X and Y dataframes

X= df.iloc[:, 1:]
X=X.drop(['locationStatus'], axis=1)
y=df['locationStatus']

In [ ]:
X.shape

(17572, 3)

In [ ]:
y.shape

(17572,)

In [ ]:
# split the dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('X_train : ')
print(X_train.head())
print('')
print('X_test : ')
print(X_test.head())
print('')
print('y_train : ')
print(y_train.head())
print('')
print('y_test : ')
print(y_test.head())

X_train : 
           timestamp  rssiOne  rssiTwo
21800  1551368240164      -95      -95
10925  1551367743074      -86      -86
18351  1551368542045      -78      -78
18222  1551368510061      -79      -79
5354   1551368184684      -74      -74

X_test : 
           timestamp  rssiOne  rssiTwo
19614  1551367682305      -70      -70
20254  1551367842318      -85      -85
8273   1551368026537      -92      -94
18259  1551368519281      -75      -75
9038   1551368310107      -88      -87

y_train : 
21800    0
10925    1
18351    2
18222    2
5354     2
Name: locationStatus, dtype: int64

y_test : 
19614    0
20254    0
8273     1
18259    2
9038     1
Name: locationStatus, dtype: int64


In [ ]:
print('X_train : ')
print(X_train.shape)
print('')
print('X_test : ')
print(X_test.shape)
print('')
print('y_train : ')
print(y_train.shape)
print('')
print('y_test : ')
print(y_test.shape)

X_train : 
(14057, 3)

X_test : 
(3515, 3)

y_train : 
(14057,)

y_test : 
(3515,)


In [ ]:
#RANDOM FOREST CLASSIFIER

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

rf = RandomForestClassifier(random_state=0, n_estimators=500)
rf.fit(X_train, y_train)
print(rf.predict(X_test))

[2 2 0 ... 2 1 1]


In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import math
# Given values
Y_true = y_test  # Y_true = Y (original values)

# calculated values
Y_pred = rf.predict(X_test)  # Y_pred = Y'

# Calculation of Mean Squared Error (MSE)
mse=mean_squared_error(Y_true,Y_pred)
rmse = math.sqrt(mse)
print(mse)
print("The difference between actual and predicted values", rmse)
print(mean_absolute_error(y_test, Y_pred))

1.1408250355618776
The difference between actual and predicted values 1.0680941136257036
0.6748221906116643


In [ ]:
#GRADIENT TREE BOOSTING CLASSIFIER

from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(learning_rate=0.01, n_estimators=500)
gb.fit(X_train, y_train)
print(gb.predict(X_test))

[2 0 0 ... 2 0 0]


In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import math
# Given values
Y_true = y_test  # Y_true = Y (original values)

# calculated values
Y_pred = gb.predict(X_test)  # Y_pred = Y'

# Calculation of Mean Squared Error (MSE)
mse=mean_squared_error(Y_true,Y_pred)
rmse = math.sqrt(mse)
print(mse)
print("The difference between actual and predicted values", rmse)
print(mean_absolute_error(y_test, Y_pred))

1.027027027027027
The difference between actual and predicted values 1.0134234194190634
0.6122332859174965


In [ ]:
#KNN CLASSIFIER

X = X_test
y =  y_test

# Instantiate and train the classifier
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=10)
clf.fit(X, y)

# Check the results using metrics
from sklearn import metrics
y_pred = clf.predict(X)
print(y_pred)
print(metrics.confusion_matrix(y_pred, y))

[0 0 0 ... 1 2 1]
[[941 411 492]
 [120 215 133]
 [337 239 627]]


In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import math
# Given values
Y_true = y_test  # Y_true = Y (original values)

# calculated values
Y_pred = clf.predict(X_test)  # Y_pred = Y'

# Calculation of Mean Squared Error (MSE)
mse=mean_squared_error(Y_true,Y_pred)
rmse = math.sqrt(mse)
print(mse)
print("The difference between actual and predicted values", rmse)
print(mean_absolute_error(y_test, y_pred))

1.2002844950213372
The difference between actual and predicted values 1.095574960932084
0.7285917496443812


In [ ]:
#LOGISTIC REGRESSION CLASSIFIER

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg_classifier.predict(X_test)

print(y_pred)
print(metrics.confusion_matrix(y_pred, y))

[0 0 0 ... 0 0 0]
[[1398  865 1252]
 [   0    0    0]
 [   0    0    0]]


In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import math
# Given values
Y_true = y_test  # Y_true = Y (original values)

# calculated values
Y_pred = logreg_classifier.predict(X_test)  # Y_pred = Y'

# Calculation of Mean Squared Error (MSE)
mse=mean_squared_error(Y_true,Y_pred)
rmse = math.sqrt(mse)
print(mse)
print("The difference between actual and predicted values", rmse)
print(mean_absolute_error(y_test, y_pred))

1.6708392603129445
The difference between actual and predicted values 1.2926094771093644
0.9584637268847795


In [ ]:
np.unique(y_pred)

array([0])

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a classification report with precision, recall, and F1-score
print(classification_report(y_test, y_pred))

Accuracy: 0.397724039829303
              precision    recall  f1-score   support

           0       0.40      1.00      0.57      1398
           1       0.00      0.00      0.00       865
           2       0.00      0.00      0.00      1252

    accuracy                           0.40      3515
   macro avg       0.13      0.33      0.19      3515
weighted avg       0.16      0.40      0.23      3515



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
#SUPPORT VECTOR MACHINE CLASSIFIER

from sklearn import svm
model = svm.SVC(kernel='rbf', degree=2, C=10)
model.fit(X_train, y_train)

from sklearn import metrics
y_pred = model.predict(X_test)
print(y_pred)
print(metrics.confusion_matrix(y_pred, y_test))


[0 0 0 ... 0 0 0]
[[1398  865 1252]
 [   0    0    0]
 [   0    0    0]]


In [ ]:
np.unique(y_pred)

array([0])

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import math
# Given values
Y_true = y_test  # Y_true = Y (original values)

# calculated values
Y_pred = model.predict(X_test)  # Y_pred = Y'

# Calculation of Mean Squared Error (MSE)
mse=mean_squared_error(Y_true,Y_pred)
rmse = math.sqrt(mse)
print(mse)
print("The difference between actual and predicted values", rmse)
print(mean_absolute_error(y_test, y_pred))

1.6708392603129445
The difference between actual and predicted values 1.2926094771093644
0.9584637268847795
